### ISSUE TITLE
beta 5 checklist

### ISSUE THREAD

**Issue by kilip** [paroki/pkrbt#135]
- [x] add author (createdBy) to  post view
- [x] add galery feature
- [x] find a way to view penjabat foto by using 3:4 resolution

**Comment by kilip** [comment]
fixed in #137
